services:
  # nginx:
  #   image: nginx:1.25.3-bookworm
  #   container_name: nginx
  #   restart: always
  #   depends_on:
  #     - goproxy
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  #     # - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "0.0.0.0:80:80"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "5"

  goproxy:
    image: gomods/athens:v0.13.0
    container_name: goproxy
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - goproxy-data:/go
      - ./download.hcl:/root/download.hcl
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ATHENS_DOWNLOAD_MODE=file:/root/download.hcl

      # - http_proxy=socks5h://127.0.0.1:443
      # - https_proxy=socks5h://127.0.0.1:443
      # - HTTP_PROXY=socks5h://127.0.0.1:443
      # - HTTPS_PROXY=socks5h://127.0.0.1:443
      # - all_proxy=socks5h://127.0.0.1:443
      # - ALL_PROXY=socks5h://127.0.0.1:443

      - no_proxy="*.ir,127.0.0.1,localhost,host.docker.internal"
      - NO_PROXY="*.ir,127.0.0.1,localhost,host.docker.internal"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  goproxy-data:
    name: goproxy-data
