services:
  nginx:
    image: nginx:1.25.3-bookworm
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "0.0.0.0:80:80"

  goproxy:
    image: gomods/athens:v0.13.0
    container_name: goproxy
    restart: always
#    ports:
#      - "8081:8081"
    volumes:
      - goproxy-data:/go

volumes:
  goproxy-data:
    name: goproxy-data
