services:
  nginx:
    image: nginx:1.25.3-bookworm
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "0.0.0.0:80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  goproxy:
    image: gomods/athens:v0.13.0
    container_name: goproxy
    restart: always
#    ports:
#      - "8081:8081"
    volumes:
      - goproxy-data:/go
      - ./download.hcl:/root/download.hcl
    environment:
      - ATHENS_DOWNLOAD_MODE=file:/root/download.hcl

      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
      - all_proxy=${PROXY}
      - ALL_PROXY=${PROXY}

      - no_proxy=${NO_PROXY}
      - NO_PROXY=${NO_PROXY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  goproxy-data:
    name: goproxy-data
